#### Read data, subset of the Amazon Product Review Dataset

In [36]:
import numpy as np

In [24]:
import sframe
products = sframe.SFrame('data2/').to_dataframe()
products

name  \
0      Stop Pacifier Sucking without tears with Thumb...   
1        Nature's Lullabies Second Year Sticker Calendar   
2        Nature's Lullabies Second Year Sticker Calendar   
3                            Lamaze Peekaboo, I Love You   
4      SoftPlay Peek-A-Boo Where's Elmo A Children's ...   
5                              Our Baby Girl Memory Book   
6      Hunnt&reg; Falling Flowers and Birds Kids Nurs...   
7      Blessed By Pope Benedict XVI Divine Mercy Full...   
8      Cloth Diaper Pins Stainless Steel Traditional ...   
9      Cloth Diaper Pins Stainless Steel Traditional ...   
10     Newborn Baby Tracker&reg; - Round the Clock Ch...   
11     Newborn Baby Tracker&reg; - Round the Clock Ch...   
12     Newborn Baby Tracker&reg; - Round the Clock Ch...   
13     Newborn Baby Tracker&reg; - Round the Clock Ch...   
14     Neurosmith - Music Blocks with Mozart Music Ca...   
15     Neurosmith - Music Blocks with Mozart Music Ca...   
16     Neurosmith - Music Blocks with Mozart Music Ca...   
17     Neurosmith - Music Blocks with Mozart Music Ca...   
18         my first fish bowl by lamaze / learning curve   
19                                    Pedal Farm Tractor   
20                  Fisher Price Nesting Action Vehicles   
21                  Fisher Price Nesting Action Vehicles   
22                  Fisher Price Nesting Action Vehicles   
23                  Fisher Price Nesting Action Vehicles   
24                  Fisher Price Nesting Action Vehicles   
25                  Fisher Price Nesting Action Vehicles   
26     Sassy Who Loves Baby? Photo Album Book with te...   
27           Earlyears: Earl E. Bird with Teething Rings   
28           Earlyears: Earl E. Bird with Teething Rings   
29      My Quiet Book, Fabric Activity Book for Children   
...                                                  ...   
53042  Beautiful Luxury Nightcap Baby Suspender Baby ...   
53043  Beautiful Luxury Nightcap Baby Suspender Baby ...   
53044  Blackcell 2pairs Infant Toddler Baby Knee Pad ...   
53045        Nuby Soft Spout Easy Grip Sippy Cup - 4 pk.   
53046  VTech Communications Safe and Sound Digital Au...   
53047  Giftoyou(TM) High Quality Lightweight Retracta...   
53048  Giftoyou(TM) High Quality Lightweight Retracta...   
53049  zTcase&trade; Bluetooth Wireless Keyboard Case...   
53050       Geleeo Universal Stroller Cooling Pad - Pink   
53051           4Moms mamaRoo Plush Infant Seat - Silver   
53052           4Moms mamaRoo Plush Infant Seat - Silver   
53053  Merry Muscles Ergonomic Jumper Exerciser Baby ...   
53054  [Different Colors Available] Newisland&reg; 79...   
53055  Vandot for Samsung Galaxy S4 / I9500 ULTRA SLI...   
53056  Nicerocker big Cute Sweet Kids Baby Girls Love...   
53057  Clevamama 3-in-1 Sleep, Sit and Play Travel Ma...   
53058        Graco Argos 65 3-in-1 Harness Booster, Link   
53059  K&amp;C Baby Bath Seat Support Sling Shower Me...   
53060  Aqueduck Faucet Extender &amp; Handle Extended...   
53061  ANDI ROSE Baby Toddlers Floral Printed Ruffle ...   
53062  Vandot 2 in1 Accessory Set 3D Leather Case Lit...   
53063  Umai Authentic Hazelwood and CHERRY RAW (Unpol...   
53064  360 Degree Rotating Cover Case for Samsung Gal...   
53065         Summer Infant Pop 'n Play Portable Playard   
53066  Freeens Cool Seat Liner Breathing with 3d Mesh...   
53067  Samsung Baby Care Washer, Stainless Platinum, ...   
53068                    Mud Pie Milestone Stickers, Boy   
53069       Best BIB for Baby - Soft Bib (Pink-Elephant)   
53070       Bouncy&reg; Inflatable Real Feel Hopping Cow   
53071  Maxboost iPhone 5S/5 Case - Protective Snap-on...   

                                                  review  rating  sentiment  
0      All of my kids have cried non-stop when I trie...     5.0          1  
1      We wanted to get something to keep track of ou...     5.0          1  
2      My daughter had her 1st baby over a year ago. ...     5.0          1  
3      One of baby'

#### Simple data transformation 

Fill na values in 'review' column 

In [26]:
products = products.fillna({'review':""})

Remove Punctuation 

In [27]:
def remove_punctuation(text):
    import string
    return text.translate(None,string.punctuation)

products['review_clean'] = products['review'].apply(remove_punctuation)

#### Read important words 

In [28]:
import json
with open ('data2/important_words.json') as data:
    important_words = json.load(data)
important_words = [str(word) for word in important_words]
important_words

['baby',
 'one',
 'great',
 'love',
 'use',
 'would',
 'like',
 'easy',
 'little',
 'seat',
 'old',
 'well',
 'get',
 'also',
 'really',
 'son',
 'time',
 'bought',
 'product',
 'good',
 'daughter',
 'much',
 'loves',
 'stroller',
 'put',
 'months',
 'car',
 'still',
 'back',
 'used',
 'recommend',
 'first',
 'even',
 'perfect',
 'nice',
 'bag',
 'two',
 'using',
 'got',
 'fit',
 'around',
 'diaper',
 'enough',
 'month',
 'price',
 'go',
 'could',
 'soft',
 'since',
 'buy',
 'room',
 'works',
 'made',
 'child',
 'keep',
 'size',
 'small',
 'need',
 'year',
 'big',
 'make',
 'take',
 'easily',
 'think',
 'crib',
 'clean',
 'way',
 'quality',
 'thing',
 'better',
 'without',
 'set',
 'new',
 'every',
 'cute',
 'best',
 'bottles',
 'work',
 'purchased',
 'right',
 'lot',
 'side',
 'happy',
 'comfortable',
 'toy',
 'able',
 'kids',
 'bit',
 'night',
 'long',
 'fits',
 'see',
 'us',
 'another',
 'play',
 'day',
 'money',
 'monitor',
 'tried',
 'thought',
 'never',
 'item',
 'hard',
 'plasti

#### Count number of appearance of important words for each review 

In [29]:
for word in important_words:
    products[word] = products['review_clean'].apply(lambda s: s.split().count(word))
products

name  \
0      Stop Pacifier Sucking without tears with Thumb...   
1        Nature's Lullabies Second Year Sticker Calendar   
2        Nature's Lullabies Second Year Sticker Calendar   
3                            Lamaze Peekaboo, I Love You   
4      SoftPlay Peek-A-Boo Where's Elmo A Children's ...   
5                              Our Baby Girl Memory Book   
6      Hunnt&reg; Falling Flowers and Birds Kids Nurs...   
7      Blessed By Pope Benedict XVI Divine Mercy Full...   
8      Cloth Diaper Pins Stainless Steel Traditional ...   
9      Cloth Diaper Pins Stainless Steel Traditional ...   
10     Newborn Baby Tracker&reg; - Round the Clock Ch...   
11     Newborn Baby Tracker&reg; - Round the Clock Ch...   
12     Newborn Baby Tracker&reg; - Round the Clock Ch...   
13     Newborn Baby Tracker&reg; - Round the Clock Ch...   
14     Neurosmith - Music Blocks with Mozart Music Ca...   
15     Neurosmith - Music Blocks with Mozart Music Ca...   
16     Neurosmith - Music Blocks with Mozart Music Ca...   
17     Neurosmith - Music Blocks with Mozart Music Ca...   
18         my first fish bowl by lamaze / learning curve   
19                                    Pedal Farm Tractor   
20                  Fisher Price Nesting Action Vehicles   
21                  Fisher Price Nesting Action Vehicles   
22                  Fisher Price Nesting Action Vehicles   
23                  Fisher Price Nesting Action Vehicles   
24                  Fisher Price Nesting Action Vehicles   
25                  Fisher Price Nesting Action Vehicles   
26     Sassy Who Loves Baby? Photo Album Book with te...   
27           Earlyears: Earl E. Bird with Teething Rings   
28           Earlyears: Earl E. Bird with Teething Rings   
29      My Quiet Book, Fabric Activity Book for Children   
...                                                  ...   
53042  Beautiful Luxury Nightcap Baby Suspender Baby ...   
53043  Beautiful Luxury Nightcap Baby Suspender Baby ...   
53044  Blackcell 2pairs Infant Toddler Baby Knee Pad ...   
53045        Nuby Soft Spout Easy Grip Sippy Cup - 4 pk.   
53046  VTech Communications Safe and Sound Digital Au...   
53047  Giftoyou(TM) High Quality Lightweight Retracta...   
53048  Giftoyou(TM) High Quality Lightweight Retracta...   
53049  zTcase&trade; Bluetooth Wireless Keyboard Case...   
53050       Geleeo Universal Stroller Cooling Pad - Pink   
53051           4Moms mamaRoo Plush Infant Seat - Silver   
53052           4Moms mamaRoo Plush Infant Seat - Silver   
53053  Merry Muscles Ergonomic Jumper Exerciser Baby ...   
53054  [Different Colors Available] Newisland&reg; 79...   
53055  Vandot for Samsung Galaxy S4 / I9500 ULTRA SLI...   
53056  Nicerocker big Cute Sweet Kids Baby Girls Love...   
53057  Clevamama 3-in-1 Sleep, Sit and Play Travel Ma...   
53058        Graco Argos 65 3-in-1 Harness Booster, Link   
53059  K&amp;C Baby Bath Seat Support Sling Shower Me...   
53060  Aqueduck Faucet Extender &amp; Handle Extended...   
53061  ANDI ROSE Baby Toddlers Floral Printed Ruffle ...   
53062  Vandot 2 in1 Accessory Set 3D Leather Case Lit...   
53063  Umai Authentic Hazelwood and CHERRY RAW (Unpol...   
53064  360 Degree Rotating Cover Case for Samsung Gal...   
53065         Summer Infant Pop 'n Play Portable Playard   
53066  Freeens Cool Seat Liner Breathing with 3d Mesh...   
53067  Samsung Baby Care Washer, Stainless Platinum, ...   
53068                    Mud Pie Milestone Stickers, Boy   
53069       Best BIB for Baby - Soft Bib (Pink-Elephant)   
53070       Bouncy&reg; Inflatable Real Feel Hopping Cow   
53071  Maxboost iPhone 5S/5 Case - Protective Snap-on...   

                                                  review  rating  sentiment  \
0      All of my kids have cried non-stop when I trie...     5.0          1   
1      We wanted to get something to keep track of ou...     5.0          1   
2      My daughter had her 1st baby over a year ago. ...     5.0          1   
3      One of b

#### Get number of product reviews that contain word 'perfect'

In [19]:
products[products["perfect"] > 0].shape

(2955, 198)

#### Convert dataframe to multi-dimensional array

In [30]:
 def get_numpy_data(dataframe, features, label):
     
    #Add constant column
    #Need to make sure 'constant' is the first column
    dataframe['constant'] = 1
    features = ['constant'] + features
    
    #Convert data into 2d array
    features_frame = dataframe[features]
    feature_matrix = features_frame.as_matrix()
    
    #Convert label into 1d array
    label_sarray = dataframe[label]
    label_array = label_sarray.as_matrix()
    
    return (feature_matrix, label_array)

feature_matrix, sentiment = get_numpy_data(products,important_words,'sentiment')

In [31]:
feature_matrix

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ..., 
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
sentiment

array([ 1,  1,  1, ..., -1, -1, -1], dtype=int64)

In [34]:
feature_matrix.shape

(53072L, 194L)

#### Estimate conditional Probability

In [45]:
def predict_probability(feature_matrix, coefficient):
    score = np.dot(feature_matrix,coefficient)
    predictions = 1 / (1 + np.exp(-score))
    return predictions


#### Compute derivative (dot product of error and feature value)

In [37]:
def feature_derivative(errors, feature):
    derivative = np.dot(errors,feature)    
    return derivative


#### Compute log likelihood

In [43]:
def compute_log_likelihood(feature_matrix, sentiment, coefficient):
    indicator = (sentiment == +1)
    scores = np.dot(feature_matrix, coefficient)
    lp = np.sum((indicator-1)*scores - np.log(1. + np.exp(-scores)))
    return lp

In [40]:
np.array([[1,2,3]])[0]

array([1, 2, 3])

#### Taking gradient step

In [51]:
from math import sqrt
def logistic_regression(feature_matrix,sentiment,initial_coefficient,step_size,max_iter):
    coefficient = np.array(initial_coefficient)
    
    for itr in xrange(max_iter):
        predictions = predict_probability(feature_matrix,coefficient)
        indicator = (sentiment == +1)
        errors = indicator - predictions
        
        for j in xrange(len(coefficient)):
            derivative = feature_derivative(errors,feature_matrix[:,j])
            coefficient[j] = coefficient[j] + step_size*derivative
            
        if itr <= 15 or (itr <= 100 and itr % 10 == 0) or (itr <= 1000 and itr % 100 == 0) or (itr <= 10000 and itr % 1000 == 0) or itr % 10000 == 0:
            lp = compute_log_likelihood(feature_matrix,sentiment,coefficient)
            print 'iteration %*d: log likelihood of observed labels = %.8f' % (int(np.ceil(np.log10(max_iter))), itr, lp)
    return coefficient


#### Start to train model (get coefficient)

In [77]:
coefficient = logistic_regression(feature_matrix,sentiment,np.zeros(194),1e-7,601)

iteration   0: log likelihood of observed labels = -36780.91768478
iteration   1: log likelihood of observed labels = -36775.13434712
iteration   2: log likelihood of observed labels = -36769.35713564
iteration   3: log likelihood of observed labels = -36763.58603240
iteration   4: log likelihood of observed labels = -36757.82101962
iteration   5: log likelihood of observed labels = -36752.06207964
iteration   6: log likelihood of observed labels = -36746.30919497
iteration   7: log likelihood of observed labels = -36740.56234821
iteration   8: log likelihood of observed labels = -36734.82152213
iteration   9: log likelihood of observed labels = -36729.08669961
iteration  10: log likelihood of observed labels = -36723.35786366
iteration  11: log likelihood of observed labels = -36717.63499744
iteration  12: log likelihood of observed labels = -36711.91808422
iteration  13: log likelihood of observed labels = -36706.20710739
iteration  14: log likelihood of observed labels = -36700.5020

#### Get scores

In [78]:
scores = np.dot(feature_matrix,coefficient)
np.where(scores > 0)[0].size

26447

#### Get accuracy

In [79]:
scores[scores>0] = 1
scores[scores<=0] = 0
scores
diff = scores - sentiment
diff

array([ 0., -1.,  0., ...,  1.,  2.,  1.])

In [80]:
np.where(diff == 0)[0].size

20007

In [81]:
sentiment.size

53072

In [82]:
np.where(diff == 0)[0].size / float(sentiment.size)

0.3769784443774495

In [84]:
coefficients = list(coefficient[1:]) # exclude intercept
word_coefficient_tuples = [(word, coefficient) for word, coefficient in zip(important_words, coefficients)]
word_coefficient_tuples = sorted(word_coefficient_tuples, key=lambda x:x[1], reverse=True)
word_coefficient_tuples

[('great', 0.12598839172757248),
 ('love', 0.12507854750346772),
 ('easy', 0.12310460697463117),
 ('loves', 0.086645204714244931),
 ('little', 0.086361150315933569),
 ('well', 0.058128946727757584),
 ('perfect', 0.057760062183670358),
 ('old', 0.038004642810596005),
 ('nice', 0.035840246186548158),
 ('daughter', 0.034245482335575617),
 ('soft', 0.033905535672018164),
 ('happy', 0.033020346647026931),
 ('fits', 0.032602456845351638),
 ('recommend', 0.030759378504994227),
 ('baby', 0.029955983818161371),
 ('best', 0.029572865363640431),
 ('also', 0.029287980619143627),
 ('comfortable', 0.02563853288442668),
 ('car', 0.023372468401985962),
 ('son', 0.02327460148504442),
 ('works', 0.023136242630726171),
 ('bit', 0.02297130029115755),
 ('clean', 0.022931922001710389),
 ('size', 0.020715194907928468),
 ('room', 0.019757294366299801),
 ('price', 0.019068075517368454),
 ('play', 0.017809162791683035),
 ('easily', 0.017291273720783436),
 ('still', 0.016843557591970267),
 ('kids', 0.01679511365

In [86]:
word_coefficient_tuples = sorted(word_coefficient_tuples, key=lambda x:x[1])
word_coefficient_tuples

[('would', -0.094348215172549321),
 ('product', -0.074435122290821373),
 ('money', -0.07414851302742434),
 ('work', -0.061650278221145244),
 ('disappointed', -0.056238759977904493),
 ('even', -0.055579673001426889),
 ('return', -0.050956226161556623),
 ('get', -0.050916450530908861),
 ('back', -0.050549916576318819),
 ('waste', -0.046172941881655556),
 ('monitor', -0.043440469168438467),
 ('thought', -0.040388685632318767),
 ('could', -0.035788050442700545),
 ('tried', -0.034938320843512415),
 ('way', -0.034294680468024183),
 ('buy', -0.033044583305475314),
 ('item', -0.032439631422854373),
 ('time', -0.031585631566127759),
 ('returned', -0.031018428498649057),
 ('broke', -0.030120561143121363),
 ('cheap', -0.028424630988713621),
 ('plastic', -0.028230279784268363),
 ('better', -0.027909398117596611),
 ('reviews', -0.027662075657780914),
 ('hard', -0.026213892846595199),
 ('thing', -0.02553334288639085),
 ('bad', -0.024341626365528342),
 ('something', -0.02418833198201659),
 ('never', 